### ISSUE TITLE
Master Passwort prompt opens 10 times when I start Firefox

### ISSUE THREAD

**Issue by RobKuebler** [sarahavilov/logmein#1]
Hi!

The addons looks nice, but whenever I start Firefox, around 10 master password prompts pop up. Everytime. Can I do something about that? Because sometimes it even crashes the fox. Sadly I have to deactivate the addon for now, although I would love using it. Thank you for your work!

Firefox 41
Fedora 22
Log me In version: from the Mozilla website (0.1.4) and also the one here: https://github.com/sarahavilov/logmein/blob/master/src/executables/extension.xpi?raw=true

**Comment by sarahavilov** [comment]
Thanks for the report. It is now fixed on the latest dev version,
https://github.com/sarahavilov/logmein/blob/master/src/executables/extension.xpi?raw=true

Download the XPI and drop it into your Firefox browser. You might need to restart once
