### ISSUE TITLE
Strange behavior (screenshot)

### ISSUE THREAD

**Issue by osminogig** [sarahavilov/logmein#5]
Hello !
Test on the clear Firefox 47
# [screenshot](http://ipic.su/img/img7/fs/2016-06-14_104008.1465890437.png)

Tested on versions :
0.1.9
0.2.0b1
# [screenshot 2](http://ipic.su/img/img7/fs/2016-06-14_111841.1465892357.png)

**Comment by sarahavilov** [comment]
Try to delete the account that is not being shown in the list and enter it in the page manually to let Firefox save it one more time. Seems like one of the logins is old and either the username or password field name is not recognized anymore.
